In [7]:
import torch
a = torch.range(1, 16)
print(type(a))

print(a,a.shape)


<class 'torch.Tensor'>
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.]) torch.Size([16])


/home/sahib/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


# View
a is a tensor that has 16 elements from 1 to 16(included).
If you want to reshape this tensor to make it a 4 x 4 tensor then you can use

a=a.view(2,8)

# Now a will be a 4 x 4 tensor. 
Note that after the reshape the total number of elements need to remain the same.
Reshaping the tensor a to a 3 x 5 tensor would not be appropriate.

# What is the meaning of parameter -1?

If there is any situation that you don't know how many rows you want but are sure of the number of columns, then you can specify this with a -1. (Note that you can extend this to tensors with more dimensions. Only one of the axis value can be -1). This is a way of telling the library: "give me a tensor that has these many columns and you compute the appropriate number of rows that is necessary to make this happen".

This can be seen in the neural network code that you have given above. After the line 
x = self.pool(F.relu(self.conv2(x))) in the forward function, you will have a 16 depth feature map. You have to flatten this to give it to the fully connected layer. So you tell pytorch to reshape the tensor you obtained to have specific number of columns and tell it to decide the number of rows by itself.

Drawing a similarity between numpy and pytorch, view is similar to numpy's reshape function.

# -1 parameter functionality defined above also works if we know number of rows but not number of columns


In [14]:
a=a.view(4,4)

print(a,a.shape)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]) torch.Size([4, 4])


# Q2

# How Pytorch tensors’ backward() accumulates gradient?
credits:-https://medium.com/@zhang_yang/how-pytorch-tensors-backward-accumulates-gradient-8d1bf675579b

#
torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.

In [70]:
x = torch.ones(1, requires_grad=True)
y = x**2
z = x**3


Create 2 variables Y and Z that depend on X

See how x.grad is accumulated from y.backward() then z.backward() : first 2 then 5 = 2 + 3, where 2 comes from dy/dx=2x=2 (evaluated at x=1)and 3 comes from dz/dx=3x**2=3 (evaluated at x=1).

In [71]:
y.backward()

In [72]:
print(x.grad)

tensor([2.])


In [73]:
z.backward()

In [74]:
x.grad

tensor([5.])

# This shows accumulation of Gradients which is not a good thing 
# while doing Gradient on Mini Batch 