In [17]:
import torch
x=torch.tensor(23,dtype=torch.float32)
x.requires_grad_(requires_grad=True) 
y=x.pow(2)

print(y)
y.backward()
print(x.grad)

tensor(529., grad_fn=<PowBackward0>)
tensor(46.)


In [40]:
# x = torch.ones(2, 2, requires_grad=True)
# print(x)
y = torch.ones(3, 3, requires_grad=True)
print(y)
z = y * y * 3
out = z.mean()

print(z, out)

out.backward()

print(y.grad)
# print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<MulBackward0>) tensor(3., grad_fn=<MeanBackward1>)
tensor([[0.6667, 0.6667, 0.6667],
        [0.6667, 0.6667, 0.6667],
        [0.6667, 0.6667, 0.6667]])
