In [3]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [4]:
env = gym.make("FrozenLake-v0")

## With this env object, we’re able to query for information about the environment, sample states and actions, retrieve rewards, and have our agent navigate the frozen lake. That’s all made available to us conveniently with Gym.



In [12]:
'''Creating the Q-table
We’re now going to construct our Q-table, and initialize all the Q-values to zero for each state-action pair.

Remember, the number of rows in the table is equivalent to the size of the state space in the environment, 
and the number of columns is equivalent to the size of the action space. We can get this information using 
using env.observation_space.n and env.action_space.n, 
as shown below. We can then use this information to build the Q-table and fill it with zeros.'''
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Initializing Q-learning parameters
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1 # EPSILON
max_exploration_rate = 1 
min_exploration_rate = 0.01 
exploration_decay_rate = 0.01 #
